import React from "react";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import "antd/dist/reset.css";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import "swiper/css/effect-fade";
import { HeaderComponent } from "@/components";
import FooterComponent from "@/components/FooterComponent";
import NextTopLoader from "nextjs-toploader";

import Link from "next/link";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{
  children: React.ReactNode;
  params: { locale: string };
}> = async ({ children, params: { locale } }) => {
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <NextTopLoader color="green" />
          <div className="fixed bottom-8 right-12 z-50 flex flex-col gap-6">
            {/* <div className="relative w-[60px] h-[60px]">
             
              <div className="absolute inset-0 flex items-center justify-center">
                <div className="w-full h-full rounded-full bg-cyan-400 opacity-50 animate-expand-circle"></div>
                <div className="w-full h-full rounded-full bg-cyan-400 opacity-50 animate-expand-circle delay-150"></div>
              </div>

             
              <Link
                href="tel:0888167247"
                target="_blank"
                className="relative z-10"
              >
                <Image
                  width={50}
                  height={50}
                  alt="Phone"
                  src="/images/phone.png"
                  className="bg-cyan-300 rounded-full "
                />
              </Link>
            </div> */}

            <Link
              href={`https://zalo.me/0888167247`}
              target="_blank"
              className="group shadow-md rounded-2xl"
            >
              <Image
                width={60}
                height={60}
                alt="Zalo"
                src="/images/zalo.png"
                className="rounded-2xl shadow-lg group-hover:scale-110 transition-transform duration-300"
              />
            </Link>
          </div>

          <HeaderComponent />
          {children}
          <FooterComponent />
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
